version: '3.8'

services:
  app:
    image: ghcr.io/sortedstartup/docker-images/dev-go-npm-grpc:jan-26-2025-2
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=devdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - "3000:3000"
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - "5432:5432"

volumes:
  postgres-data:
  node_modules: 